# Generated by Django 4.1.2 on 2022-11-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='services',
            field=models.CharField(choices=[('Obedience-Training', 'Obedience-Training'), ('Trick_Skill_Training', 'Trick_Skill_Training'), ('Behavior Modification', 'Behavior Modification'), ('Puppy Training', 'Puppy Training'), ('Security Program', 'Security Program'), ('Separation Anxiety', 'Separation Anxiety')], max_length=50),
        ),
    ]
