# Generated by Django 4.1.2 on 2022-11-23 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_date_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
