# Generated by Django 4.1.2 on 2022-11-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_service_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
