# Generated by Django 4.1.2 on 2022-11-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
