# Generated by Django 4.1.2 on 2022-11-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_trainer_services_delete_service'),
        ('mainapp', '0004_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('obedience', 'Obedience-Training'), ('trick', 'Trick_Skill_Training'), ('behavior', 'Behavior Modification'), ('puppy', 'Puppy Training'), ('security', 'Security Program'), ('anxiety', 'Separation Anxiety')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='accounts.trainer')),
            ],
        ),
    ]
