# Generated by Django 4.1.2 on 2022-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
