# Generated by Django 4.1.2 on 2022-11-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_trainer_services_delete_service'),
        ('mainapp', '0005_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessHours',
            new_name='Hours',
        ),
        migrations.RemoveConstraint(
            model_name='hours',
            name='start_before_end',
        ),
    ]
