# Generated by Django 4.1.2 on 2022-11-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mainapp', '0005_alter_book_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='accounts.trainer'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.owner'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
