# Generated by Django 4.1.2 on 2022-11-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mainapp', '0006_alter_book_trainer_alter_book_user_delete_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Booking',
        ),
    ]
