# Generated by Django 4.1.2 on 2022-11-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_trainer_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='services',
        ),
    ]
