# Generated by Django 4.1.2 on 2022-11-14 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_trainer_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Obedience-Training', 'Obedience-Training'), ('Trick_Skill_Training', 'Trick_Skill_Training'), ('Behavior Modification', 'Behavior Modification'), ('Puppy Training', 'Puppy Training'), ('Security Program', 'Security Program'), ('Separation Anxiety', 'Separation Anxiety')], max_length=100), blank=True, null=True, size=None),
        ),
    ]
