# Generated by Django 4.1.2 on 2022-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_trainer_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(choices=[('obedience', 'Obedience-Training'), ('trick', 'Trick_Skill_Training'), ('behavior', 'Behavior Modification'), ('puppy', 'Puppy Training'), ('security', 'Security Program'), ('anxiety', 'Separation Anxiety')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='services',
            field=models.ManyToManyField(to='accounts.service'),
        ),
    ]
