# Generated by Django 4.1.2 on 2022-11-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_trainer_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='min_price',
        ),
        migrations.AddField(
            model_name='trainer',
            name='price_charge',
            field=models.FloatField(default=1000.0),
        ),
    ]
