# Generated by Django 4.1.2 on 2022-11-21 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userlogin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to=settings.AUTH_USER_MODEL),
        ),
    ]
