# Generated by Django 4.1.2 on 2022-11-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_trainer_max_price_remove_trainer_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='price_charge',
            field=models.IntegerField(default=1000),
        ),
    ]
