# Generated by Django 4.1.2 on 2022-11-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_service_trainer_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='services',
            field=models.ManyToManyField(choices=[('obedience', 'Obedience-Training'), ('trick', 'Trick_Skill_Training'), ('behavior', 'Behavior Modification'), ('puppy', 'Puppy Training'), ('security', 'Security Program'), ('anxiety', 'Separation Anxiety')], to='accounts.service'),
        ),
    ]
