# Generated by Django 4.1.2 on 2022-11-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_trainer_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='services',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
